services:
  tmoney-postgres:
    container_name: tmoney-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./.postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - tmoney-network
    restart: unless-stopped
  tmoney-redis:
    image: redis:alpine
    volumes:
      - ./.redis:/data
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    restart: always
  #tmoney-api:
  #  container_name: tmoney-api
  #  build:
  #    context: "."
  #    dockerfile: Dockerfile
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - .:/usr/src/app
  #    - /usr/src/app/node_modules
  #  depends_on:
  #    - tmoney-postgres
  #  networks:
  #    - tmoney-network

networks:
  tmoney-network:
    driver: bridge
