import { ArgsType, Field } from '@nestjs/graphql';

@ArgsType()
export class MerchantPayQRArgs {
  @Field(() => String)
  id: string; // id of the merchant payment, generated by us. Can't use merchant's checkout id as there may be multiple merchants that use the same checkout id
}
