import { ArgsType, Field } from '@nestjs/graphql';
import { IsPositive } from 'class-validator';
import { Currency } from 'src/enums/currency.enum';

@ArgsType()
export class MerchantRequestQRArgs {
  @Field(() => String)
  orderId: string; // idempotent order ID generated by the merchant, used to identify the order

  @Field(() => Number)
  @IsPositive()
  amount: number;

  @Field(() => Currency)
  currency: Currency;
}
